name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types:
      [created, edited, deleted]
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: condition Standard
        if: ${{ (!(contains(github.event.issue.title,'(AzDevOps AB#') && (github.event.action == 'created') )) && (github.event.label.name != 'bug') && (github.event.label.name != 'Bug') && (github.event.label.name != 'task') && (github.event.label.name != 'Task')  }}
        uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ SECRETS.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ SECRETS.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "${{ SECRETS.ADO_ORGANIZATION }}"
          ado_project: "${{ SECRETS.ADO_PROJECT }}"
          ado_wit: "Issue"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100
      - name: condition Bug
        if: ${{ (!(contains(github.event.issue.title,'(AzDevOps AB#') && (github.event.action == 'created') )) && ((github.event.label.name == 'bug') || (github.event.label.name == 'Bug'))}}
        uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ SECRETS.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ SECRETS.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "${{ SECRETS.ADO_ORGANIZATION }}"
          ado_project: "${{ SECRETS.ADO_PROJECT }}"
          ado_wit: "Bug"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100
     # - name: condition Task
     #   if: ${{ (github.event.label.name == 'task') || (github.event.label.name == 'Task')}}
     #   uses: danhellem/github-actions-issue-to-work-item@master
     #   env:
     #     ado_token: "${{ SECRETS.ADO_PERSONAL_ACCESS_TOKEN }}"
     #     github_token: "${{ SECRETS.GH_PERSONAL_ACCESS_TOKEN }}"
     #     ado_organization: "${{ SECRETS.ADO_ORGANIZATION }}"
     #     ado_project: "${{ SECRETS.ADO_PROJECT }}"
     #     ado_wit: "Task"
     #     ado_new_state: "New"
     #     ado_active_state: "Active"
     #     ado_close_state: "Closed"
     #     ado_bypassrules: true
     #     log_level: 100
      #- name: Test json
       # run: echo "${{ toJSON(github) }}"
      - name: Test title
        run: echo "${{ github.event.issue.title }}"

